In [1]:
import pandas as pd

Encoding can be done using different way two of them are done below:
1. Label Encoding
2. Ordinal Encoding

**Label Encoding**

Label Encoding is done on Nominal data that donot follow a sequence like names of different animals (cow, cat, dog, elephant, etc.)

In [10]:
dataset = pd.read_csv('../teams.csv')
dataset.head(3)

,code,current,team,team_gender,country_code,country,country_long,discipline,disciplines_code,events,athletes,coaches,athletes_codes,num_athletes,coaches_codes,num_coaches
0,ARCMTEAM3---CHN01,True,People's Republic of China,M,CHN,China,People's Republic of China,Archery,ARC,Men's Team,"['KAO Wenchao', 'LI Zhongyuan', 'WANG Yan']",NaN,"['1913366', '1913367', '1913369']",3.0,NaN,NaN
1,ARCMTEAM3---COL01,True,Colombia,M,COL,Colombia,Colombia,Archery,ARC,Men's Team,"['ARCILA Santiago', 'ENRIQUEZ Jorge', 'HERNAND...",NaN,"['1935642', '1543412', '1935644']",3.0,NaN,NaN
2,ARCMTEAM3---FRA01,True,France,M,FRA,France,France,Archery,ARC,Men's Team,"['ADDIS Baptiste', 'CHIRAULT Thomas', 'VALLADO...",NaN,"['1541270', '1541272', '1541275']",3.0,NaN,NaN

In [11]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [12]:
dataset.columns

Index(['code', 'current', 'team', 'team_gender', 'country_code', 'country',
       'country_long', 'discipline', 'disciplines_code', 'events', 'athletes',
       'coaches', 'athletes_codes', 'num_athletes', 'coaches_codes',
       'num_coaches'],
      dtype='object')

In [13]:
dataset['coaches']

0                                                     NaN
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
                              ...
1693    ['KAMMENOU Alexia Anna', 'LEMPESIS Xenofon', '...
1694    ['CSEH Sandor Viktor', 'KARDOS Krisztina', 'MI...
1695    ['SILIPO Carlo', 'di CECCA Cosimino', 'GIGLI E...
1696    ['YPERLAAN Ineke', 'van ECK Richard', 'DOUDESI...
1697    ['CAHILL Molly', 'KRIKORIAN Adam', 'OEDING Chr...
Name: coaches, Length: 1698, dtype: object

In [14]:
dataset['coaches_en'] = dataset['coaches'].fillna(dataset['coaches'].mode()[0], inplace=True)

In [16]:
dataset.tail(10)

,code,current,team,team_gender,country_code,country,country_long,discipline,disciplines_code,events,athletes,coaches,athletes_codes,num_athletes,coaches_codes,num_coaches,coaches_en
1688,WPOWTEAM7---AUS01,True,Australia,W,AUS,Australia,Australia,Water Polo,WPO,Women,"['PALM Gabriella', 'GOFERS Keesja', 'ARMIT Ell...","['DENIS Eddie', 'RIPPON Bec', 'WOODS Taryn', '...","['1947514', '1947523', '1947513', '1947506', '...",13.0,"['1947628', '1947636', '1947637', '9450002', '...",5.0,None
1689,WPOWTEAM7---CAN01,True,Canada,W,CAN,Canada,Canada,Water Polo,WPO,Women,"['GAUDREAULT Jessica', 'LEKNESS Rae', 'CREVIER...","['PARADELO David', 'POSTERIVO Stefano', 'CAMPB...","['1967398', '1967408', '1967389', '1967403', '...",13.0,"['1967468', '1967471', '1967472', '9450006', '...",5.0,None
1690,WPOWTEAM7---CHN01,True,People's Republic of China,W,CHN,China,People's Republic of China,Water Polo,WPO,Women,"['DONG Wenxin', 'YAN Siya', 'YAN Jing', 'XIONG...","['GOMEZ AGUERA Salvador Emilio', 'JANE GIRALT ...","['1927247', '1927261', '1927262', '1927260', '...",13.0,"['1927270', '1927271', '1927274', '9450008', '...",5.0,None
1691,WPOWTEAM7---ESP01,True,Spain,W,ESP,Spain,Spain,Water Polo,WPO,Women,"['ESTER RAMOS Laura', 'PIRALKOVA COELLO Isabel...","['ANDREO GABAN Angel Luis', 'OCA GAIA Miguel A...","['1954878', '1954897', '1954877', '1954893', '...",13.0,"['1957222', '1957226', '1957227', '9450023', '...",5.0,None
1692,WPOWTEAM7---FRA01,True,France,W,FRA,France,France,Water Polo,WPO,Women,"['RYCRAW Mia', 'ANDRES Lara', 'HEURTAUX Valent...","['LORANTOS Theodoros', 'DERENTY Lorene', 'BELL...","['1906407', '1906383', '1906399', '1906391', '...",13.0,"['1906448', '1906454', '9450039']",3.0,None
1693,WPOWTEAM7---GRE01,True,Greece,W,GRE,Greece,Greece,Water Polo,WPO,Women,"['DIAMANTOPOULOU Chrysoula', 'PLEVRITOU Elefth...","['KAMMENOU Alexia Anna', 'LEMPESIS Xenofon', '...","['1954594', '1954604', '1954651', '1954595', '...",13.0,"['1968484', '1968489', '1968491', '9450016', '...",5.0,None
1694,WPOWTEAM7---HUN01,True,Hungary,W,HUN,Hungary,Hungary,Water Polo,WPO,Women,"['MAGYARI Alda', 'SZILAGYI Dorottya', 'VALYI V...","['CSEH Sandor Viktor', 'KARDOS Krisztina', 'MI...","['1941170', '1942706', '1942736', '1940978', '...",13.0,"['1940930', '1941075', '1941198', '9450004', '...",5.0,None
1695,WPOWTEAM7---ITA01,True,Italy,W,ITA,Italy,Italy,Water Polo,WPO,Women,"['CONDORELLI Giuseppina Aurora', 'TABANI Chiar...","['SILIPO Carlo', 'di CECCA Cosimino', 'GIGLI E...","['1925809', '1925820', '1925811', '1925805', '...",13.0,"['1925566', '1925620', '9450001', '9450019', '...",5.0,None
1696,WPOWTEAM7---NED01,True,Netherlands,W,NED,Netherlands,Netherlands,Water Polo,WPO,Women,"['AARTS Laura', 'WOLVES Iris', 'SLEEKING Brigi...","['YPERLAAN Ineke', 'van ECK Richard', 'DOUDESI...","['1968845', '1968848', '1968857', '1968858', '...",13.0,"['1968864', '1968868', '1968871', '9450033', '...",5.0,None
1697,WPOWTEAM7---USA01,True,United States of America,W,USA,United States,United States of America,Water Polo,WPO,Women,"['JOHNSON Ashleigh', 'MUSSELMAN Maddie', 'PREN...","['CAHILL Molly', 'KRIKORIAN Adam', 'OEDING Chr...","['1908378', '1908383', '1908385', '1908375', '...",13.0,"['1908408', '1908409', '1908410', '9450035', '...",5.0,None

In [20]:
dataset['coaches']=le.fit_transform(dataset['coaches'])

In [21]:
dataset['coaches']

0        92
1        92
2        92
3        92
4        92
       ...
1693    134
1694     54
1695    204
1696    228
1697     32
Name: coaches, Length: 1698, dtype: int32

The label encoding on nominal data is not reccommneded. Data Scientists use Ordinal encoding mostly.

**Ordinal Encoding**

Ordinal Encoding is done using two ways:
1. Using sklearn library
2. Map function

In [22]:
df = pd.DataFrame({'size': ['s','m','x','s','m','xl','m','x','s','s','m','xl','m','m','x','s',]})
df.head(5)

  size
0    s
1    m
2    x
3    s
4    m

In [29]:
ord_data = [['s','m','l','x','xl']]

In [30]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=ord_data)

In [31]:
oe.fit(df[['size']])

OrdinalEncoder(categories=[['s', 'm', 'l', 'x', 'xl']])

In [32]:
df['en_size'] = oe.transform(df[['size']])

In [33]:
df

   size  en_size
0     s      0.0
1     m      1.0
2     x      3.0
3     s      0.0
4     m      1.0
5    xl      4.0
6     m      1.0
7     x      3.0
8     s      0.0
9     s      0.0
10    m      1.0
11   xl      4.0
12    m      1.0
13    m      1.0
14    x      3.0
15    s      0.0

Now performing ordinal encoding with map function

In [35]:
df1 = pd.DataFrame({'size': ['s','m','x','s','m','xl','m','x','s','s','m','xl','m','m','x','s',]})

In [39]:
ord_data_new = {'s':0, 'm':1,'x':2, 'xl':3}

In [40]:
df1['size'].map(ord_data_new)

0     0
1     1
2     2
3     0
4     1
5     3
6     1
7     2
8     0
9     0
10    1
11    3
12    1
13    1
14    2
15    0
Name: size, dtype: int64

In [42]:
df1['size_en'] = df1['size'].map(ord_data_new)

In [43]:
df1

   size  size_en
0     s        0
1     m        1
2     x        2
3     s        0
4     m        1
5    xl        3
6     m        1
7     x        2
8     s        0
9     s        0
10    m        1
11   xl        3
12    m        1
13    m        1
14    x        2
15    s        0